### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by sovalyeler** [bojanraic/spicetify-private-session#1]
I'm on Spotify (64 bit) 1.2.24.756.g7a7fc7f0 and Spicetify v2.27.0. Does not work. Needs updating.

**Comment by bojanraic** [comment]
Thanks for the report. Which OS are you on, @sovalyeler? I just upgraded Spotify on my Mac, and ran `spicetify backup apply` and the private-session is enabled at start, as expected.

**Comment by bojanraic** [comment]
Additionally, it seems no major CSS changes were introduced in this version that would impact the selectors for this extension, so without details about OS/OS version, it's a bit difficult to reproduce. 
Try doing a backup restore and then a clean backup apply/install from marketplace. 
Hope that helps.

**Comment by bojanraic** [comment]
Thanks for the follow up. However, I'm still not clear on the OS version you are using. Also, what is loopyLoop.js, how did you install it and what does it have to do with spicetify? 

If it is not related to spicetify, I'm not sure it warrants looking into further, especially if the extension works when loopyLoop.js is disabled/removed. 
Please provide additional information so I can determine whether to investigate further or not.

**Comment by bojanraic** [comment]
Got it. I'll try to investigate this when I get some time.

**Comment by bojanraic** [comment]
@sovalyeler Updated the menu item matching logic. Should work now. Please test and confirm.
